@startuml
skinparam ClassAttributeIconSize 0
class Game {
board:let
borderRight:let
borderLeft:let
temp:let
buttonCountlet
cntr:let
player:let
index1:let
index2:let
buttons:let
mainPanel:let
c Game()
createBoard(set:let):void
updateBoard():void
performPlay(index1:let, index2:let):void
markFields(validMoves:let,index1:let):void
validation(index1:let,operator:let,color:let):let
prepareRook(validMoves:let,color:let,king:let):void
prepareBishop(validMoves:let,color:let,king:let):void
pawn(validMoves:let,operator:int,color:let):void
bishop(validMoves:let, operator:let, color:let, number:let, array:let, king:let):void
checkBorder(validIndex:let, array:let):let
knight(validMoves:let, operator:let, color:let, number:let, array:let):void
}
@enduml